sample: "chr21"

fastq:
  r1: "data/HG002_R1_wgs_chr21.fastq.gz"
  r2: "data/HG002_R2_wgs_chr21.fastq.gz"

reference:
  fa: "ref/chr21.fa"

# Tool parameters


# Output directories
results_dir: "results"

# Final output specification
final_output:
  filename: "sv_calls.csv"
  columns: ["CHROM", "START", "END", "SIZE", "QUAL", "FILTER"]
