sample: "chr21"

fastq:
  r1: "data/HG002_R1_wgs_chr21.fastq.gz"
  r2: "data/HG002_R2_wgs_chr21.fastq.gz"

reference:
  fa: "ref/chr21.fa"

# Resource configuration
threads:
  bwa_align: 4
  sort_bam: 4
  index_bam: 1
  delly_call: 1

# Tool parameters
delly:
  min_sv_size: 50
  max_sv_size: 1000000
  sv_types: ["DEL", "DUP", "INV", "INS", "TRA"]

# Output directories
results_dir: "results"
logs_dir: "logs"

# Final output specification
final_output:
  filename: "sv_calls.csv"
  columns: ["CHROM", "START", "END", "SIZE", "QUAL", "FILTER"]
