sample: "HG002"

reference:
  fa: "workflow/data/fasta/chr21.fa"

fastq:
  r1: "workflow/data/HG002_R1_wgs_chr21.fastq.gz"
  r2: "workflow/data/HG002_R2_wgs_chr21.fastq.gz"

file_exts:
  fasta: .fa
  bwa_idx:
    - .bwt
    - .amb
    - .ann
    - .pac
    - .sa
  fasta_idx: .fai  
  bam: .bam
  bam_idx: .bam.bai
  vcf: .vcf
  bcf: .bcf
 

# Tool-specific configurations
tools:
  bwa:
    threads: 4
    memory: 4096
    outdir: workflow/data/fasta

  samtools:
    threads: 4
    memory: 2048
    outdir: workflow/data/fasta

  fastqc:
    threads: 1
    memory: 1024
    outdir: workflow/reports

  alignment:
    threads: 4
    memory: 2048
    outdir: workflow/data/bam

  delly:
    threads: 2
    memory: 8192
    outdir: workflow/data/delly
    sv_types:
          - BND  # translocation
          - DEL  # deletion
          - DUP  # duplication
          - INS  # insertion
          - INV  # inversion

# Final output configuration
final_output:
  filename: "structural_variants.csv"
  columns: ["CHROM", "START", "END", "SIZE", "QUAL", "FILTER", "SVTYPE"]
  results_dir: "workflow/reports/"
